### PR TITLE
#1 add local dogu registry

### LINKED ISSUE #1: Create Library and add local Dogu registry

### PR DESCRIPTION
**Pull request by jelemux**
Resolves #1

### CODE REVIEW

**Comment by nhinze23** [comment]
ces-build-lib v2.2.0 is available

**Comment by nhinze23** [comment]
lgtm :)

**Comment by jelemux** [comment]
> I think the sonar project version can be deleted. If not, we have to template it in the release process with the `release_args.sh`.

Have we ever done that in any of our projects? What benefit does it bring?

**Comment by nhinze23** [comment]
> > I think the sonar project version can be deleted. If not, we have to template it in the release process with the `release_args.sh`.
> 
> Have we ever done that in any of our projects? What benefit does it bring?

I think no and the version is just displayed in the sonar ui if the main branch is selected.

**Pull request merged**
